### ISSUE TITLE
[BUG: Breaking] Marker is 20x+ slower since v1.9.0+ in Mac

### ISSUE THREAD

**Issue by axsaucedo** [VikParuchuri/marker#960]
## 🧨 Describe the Bug

Marker is at least 20x slower in Mac since since version v1.9.0.

If using Marker on a mac install `pip install marker==1.8.0` as the fix.

## 📄 Input Document

This works with any PDF when run in Mac with M1+ chip.

## 📤 Output Trace / Stack Trace

It may be due to this warning (but may not be the case):

```
2025-12-13 15:17:09,820 [WARNING] surya: `TableRecEncoderDecoderModel` is not compatible with mps backend. Defaulting to cpu instead
```

## ⚙️ Environment

Please fill in all relevant details:

- **Marker version**: Any version 1.9.0+
- **Operating System**: Mac

## ✅ Expected Behavior

What did you expect Marker to do?

Not be 20x slower in newer versions.

## 📟 Command or Code Used

Any command works. Here's an example:

```
marker --output_dir ./output/ ./
```

**Comment by mntolia** [comment]
Can confirm its very slow on my mac m4 pro. 
Had to downgrade it to make it performant

**Comment by uts58** [comment]
Same for me, I thought it was normal

**Comment by axn236** [comment]
Found the root cause. In v0.16.0, the devs added a block in `surya/table_rec/loader.py` that forces `TableRecEncoderDecoderModel` to fall back to CPU when MPS is detected - presumably to stop an underlying incompatibility. The actual issue is that PyTorch's MPS backend silently produces incorrect results from `scaled_dot_product_attention` when operating on non-contiguous tensors during batch processing.

The fix is to add `.contiguous()` calls before SDPA operations and use float32 on MPS (same speed as bfloat16, but more reliable). Tested on M4 MacBook Pro (16GB), PyTorch 2.9.1, Surya 0.17.0, Python 3.13. Full MPS support with batching restored.

Seven files require modification:

**`surya/common/adetr/decoder.py`** (Table Recognition)

The ADETR decoder lacks the MPS-compatible autocast handling present in the Qwen2 decoder. In `SuryaADETRDecoderRotaryEmbedding.forward()` (~line 78):

```python
device_type = x.device.type
device_type = (
    device_type
    if isinstance(device_type, str) and device_type != "mps"
    else "cpu"
)
with torch.autocast(device_type=device_type, enabled=False):
    # existing freqs calculation...
```

Add `.contiguous()` before both SDPA calls in `SuryaADETRDecoderSdpaCrossAttention.forward()` and `SuryaADETRDecoderSdpaAttention.forward()`:

```python
query_states = query_states.contiguous()
key_states = key_states.contiguous()
value_states = value_states.contiguous()
if causal_mask is not None:
    causal_mask = causal_mask.contiguous()
```

Fix cache functions (`_update_static_cache`, `_update_dynamic_cache`) to return contiguous tensors:

```python
return k_out.contiguous(), v_out.contiguous()
```

**`surya/table_rec/loader.py`**

Replace the MPS block with float32 enforcement:

```python
if device == "mps":
    dtype = torch.float32
```

**`surya/table_rec/__init__.py`**

Re-enable MPS batching (set to 8 to match CPU), add `.contiguous()` after encoder output and `torch.stack`:

```python
encoder_hidden_states = self.model.encoder(pixel_values=batch_pixel_values).last_hidden_state
encoder_hidden_states = encoder_hidden_states.contiguous()
```

```python
row_encoder_hidden_states = torch.stack(row_encoder_hidden_states).contiguous()
```

**`surya/common/surya/encoder/__init__.py`** (Foundation Model - Layout, OCR)

Both `Qwen2_5_VLVisionXLASdpaAttention.forward()` and `Qwen2_5_VLVisionSdpaAttention.forward()` have q, k, v from `reshape().permute().unbind()` then `transpose()` - non-contiguous. Add `.contiguous()` after each transpose before SDPA:

```python
q = q.transpose(1, 2).contiguous()
k = k.transpose(1, 2).contiguous()
v = v.transpose(1, 2).contiguous()
```

**`surya/foundation/loader.py`** (Foundation Model loader)

Use float32 on MPS (same speed as bfloat16, more reliable):

```python
if device == "mps":
    dtype = torch.float32
```

**`surya/common/donut/encoder.py`** (Detection)

`transpose_for_scores` returns non-contiguous tensor. Add `.contiguous()`:

```python
def transpose_for_scores(self, x):
    new_x_shape = x.size()[:-1] + (
        self.num_attention_heads,
        self.attention_head_size,
    )
    x = x.view(new_x_shape)
    return x.permute(0, 2, 1, 3).contiguous()
```

Note: `transpose_kv_for_scores` already has `.contiguous()`.

**`surya/detection/loader.py`** (Detection Model loader)

Use float32 on MPS:

```python
if device == "mps":
    dtype = torch.float32
```

Tensors from `transpose()`, `view()`, `permute()`, cache slicing, `torch.cat()`, and `torch.stack()` are not guaranteed contiguous. MPS SDPA fails silently on these. After these changes, MPS batch output matches CPU exactly.

**Comment by sp-cega** [comment]
> Found the root cause. In v0.16.0, the devs added a block in `surya/table_rec/loader.py` that forces `TableRecEncoderDecoderModel` to fall back to CPU when MPS is detected - presumably to stop an underlying incompatibility. The actual issue is that PyTorch's MPS backend silently produces incorrect results from `scaled_dot_product_attention` when operating on non-contiguous tensors during batch processing.
> 
> The fix is to add `.contiguous()` calls before SDPA operations and use float32 on MPS (same speed as bfloat16, but more reliable). Tested on M4 MacBook Pro (16GB), PyTorch 2.9.1, Surya 0.17.0, Python 3.13. Full MPS support with batching restored.
> 
> Seven files require modification:
> 
> **`surya/common/adetr/decoder.py`** (Table Recognition)
> 
> The ADETR decoder lacks the MPS-compatible autocast handling present in the Qwen2 decoder. In `SuryaADETRDecoderRotaryEmbedding.forward()` (~line 78):
> 
> device_type = x.device.type
> device_type = (
>     device_type
>     if isinstance(device_type, str) and device_type != "mps"
>     else "cpu"
> )
> with torch.autocast(device_type=device_type, enabled=False):
>     # existing freqs calculation...
> Add `.contiguous()` before both SDPA calls in `SuryaADETRDecoderSdpaCrossAttention.forward()` and `SuryaADETRDecoderSdpaAttention.forward()`:
> 
> query_states = query_states.contiguous()
> key_states = key_states.contiguous()
> value_states = value_states.contiguous()
> if causal_mask is not None:
>     causal_mask = causal_mask.contiguous()
> Fix cache functions (`_update_static_cache`, `_update_dynamic_cache`) to return contiguous tensors:
> 
> return k_out.contiguous(), v_out.contiguous()
> **`surya/table_rec/loader.py`**
> 
> Replace the MPS block with float32 enforcement:
> 
> if device == "mps":
>     dtype = torch.float32
> **`surya/table_rec/__init__.py`**
> 
> Re-enable MPS batching (set to 8 to match CPU), add `.contiguous()` after encoder output and `torch.stack`:
> 
> encoder_hidden_states = self.model.encoder(pixel_values=batch_pixel_values).last_hidden_state
> encoder_hidden_states = encoder_hidden_states.contiguous()
> row_encoder_hidden_states = torch.stack(row_encoder_hidden_states).contiguous()
> **`surya/common/surya/encoder/__init__.py`** (Foundation Model - Layout, OCR)
> 
> Both `Qwen2_5_VLVisionXLASdpaAttention.forward()` and `Qwen2_5_VLVisionSdpaAttention.forward()` have q, k, v from `reshape().permute().unbind()` then `transpose()` - non-contiguous. Add `.contiguous()` after each transpose before SDPA:
> 
> q = q.transpose(1, 2).contiguous()
> k = k.transpose(1, 2).contiguous()
> v = v.transpose(1, 2).contiguous()
> **`surya/foundation/loader.py`** (Foundation Model loader)
> 
> Use float32 on MPS (same speed as bfloat16, more reliable):
> 
> if device == "mps":
>     dtype = torch.float32
> **`surya/common/donut/encoder.py`** (Detection)
> 
> `transpose_for_scores` returns non-contiguous tensor. Add `.contiguous()`:
> 
> def transpose_for_scores(self, x):
>     new_x_shape = x.size()[:-1] + (
>         self.num_attention_heads,
>         self.attention_head_size,
>     )
>     x = x.view(new_x_shape)
>     return x.permute(0, 2, 1, 3).contiguous()
> Note: `transpose_kv_for_scores` already has `.contiguous()`.
> 
> **`surya/detection/loader.py`** (Detection Model loader)
> 
> Use float32 on MPS:
> 
> if device == "mps":
>     dtype = torch.float32
> Tensors from `transpose()`, `view()`, `permute()`, cache slicing, `torch.cat()`, and `torch.stack()` are not guaranteed contiguous. MPS SDPA fails silently on these. After these changes, MPS batch output matches CPU exactly.

I implemented these changes and the warning indeed went away (thanks!). The runtime did not change though, and Marker is still extremely slow (relative to previous versions). The results are better, but not by much.

**Comment by papatistos** [comment]
@sp-cega when you say
> The runtime did not change though, and Marker is still extremely slow (relative to previous versions). 

can you clarify whether it is slow _even though_ it now uses the GPU or because it still uses the CPU?

**Comment by frontierkodiak** [comment]
**M1 Max findings: GPU-routed but decode-bound — and surya2 doesn't fix Apple Silicon either.**

Controlled run on M1 Max (64 GB), power-gated, against the marker 1.8.0 baseline (18-page fixture ≈ **18.5 s** total).

**marker 1.10 / surya 0.17 (the regression):**
- The slow stage is the **foundation recognition decode loop**, and it is **MPS-routed, not CPU-bound** (device + SDPA traces confirm): it dominates runtime at ~560 decode steps @ ~0.17 s/step — the *same* decode count as CUDA, ~4.4× slower per step.
- Each step is single-token (q_len=1) GQA attention over a ~2.5k KV cache, per layer. PyTorch-MPS has no fused/flash attention for this shape → it's dispatch/latency-bound. It is **insensitive** to fp32-vs-bf16 (~1.07×), SDPA vs eager vs `enable_gqa` vs hand-rolled grouped matmul (all ≤3%), and to the `.contiguous()` set from the #960 community patch (patched ≈ stock in *time*). So that patch is a **correctness** fix, not a speed one — consistent with the earlier follow-up here.
- `torch.compile` recovers ~2.6–3.4× (fp32/bf16) on the decode *forward* in isolation, but is **net-negative end-to-end**: enabling it requires the static KV cache, which forces the layout model to pad short sequences to the full cache length (~16× slower there), and recompile churn doesn't amortize.

**surya 0.20 ("surya2", full-page VLM on llama.cpp Metal):**
- `surya-ocr==0.20.0` + `surya-ocr-2` GGUF on `llama-server` (Metal confirmed active): same fixture = **526 s (~29 s/page)**. Generation-bound — the VLM transcribes each page autoregressively (~3.7k tokens/page at ~160 tok/s aggregate). Output quality is good; throughput is ~28× the 1.8.0 wall.

**Takeaway:** on Apple Silicon, *both* the 1.9–1.10 foundation stack and surya2 are decode/generation-bound; neither is fast without a discrete GPU. `pip install marker-pdf==1.8.0` remains the fast local pin; otherwise route conversion to a CUDA host. A genuine MPS fix is a fused-attention / generation-throughput problem (PyTorch-MPS, llama.cpp-Metal) more than a marker-level one.
